# 应用服务 WEB 访问端口
server:
  port: 8081
# 应用名称
spring:
  application:
    name: nacos-provider
  # Nacos认证信息
  cloud:
    nacos:
      discovery:
        username: root
        password: root
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: localhost:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public