server:
  port: 8080
# 应用名称
spring:
  application:
    name: mybatis-plus
# 应用服务 WEB 访问端口
# 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #建表脚本位置
    schema: classpath:db/t_user.sql,classpath:db/t_product.sql
    #数据脚本位置
    data: classpath:db/t_user_data.sql,classpath:db/t_product_data.sql
    url: jdbc:mysql://localhost:3306/mybatis-plus?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: CJH1228793447*
    #初始化脚本语句
    initialization-mode: ALWAYS
#sql日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mybatis默认映射文件路径可以不用设置，为resource下mapper文件夹的任意xml文件
  mapper-locations: classpath*:/mapper/**/*.xml
  ##mybatis-plus全局配置
  global-config:
    db-config:
      #实体类对应的表前缀
      table-prefix: "t_"
      #全局主键生成策略
      id-type: auto
      # 全局逻辑删除的实体字段名或者删除字段上添加@TableLogic注解
      logic-delete-field: isDeleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 0
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 1