# 应用名称
spring:
  application:
    name: mybatis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    #数据脚本位置
    schema: classpath:sql/student.sql
    #初始化脚本语句
    initialization-mode: ALWAYS
    # 连接池配置
    # 初始化连接池大小
    initial-size: 5
    # 连接池中的最小空闲连接
    min-idle: 5
    # 连接池最大连接数
    max-active: 20
    # 连接等待超时时间
    max-wait: 30000
#下面这些内容是为了让MyBatis映射
mybatis:
  #指定Mybatis的Mapper文件
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.cjh.mybatis.mybatis.entity


