security:
  oauth2:
    client:
      client-id: test
      client-secret: test1234
      registered-redirect-uri: http://www.baidu.com

spring:
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password: root